get branch from tag

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -10,26 +10,26 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v4
-      - name: Extract branch name from tag reference
-        id: extract_branch
-        run: |
-          if [[ $GITHUB_REF =~ refs/tags/release\.([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
-            BRANCH_NAME="main"
-          elif [[ $GITHUB_REF =~ refs/tags/release\.([0-9]+)\.([0-9]+)\.([0-9]+)-rc\.([0-9]+)$ ]]; then
-            X=${BASH_REMATCH[1]}
-            Y=${BASH_REMATCH[2]}
-            Z=${BASH_REMATCH[3]}
-            BRANCH_NAME="release/$X.$Y.$Z"
-          else
-            TAG_NAME=${GITHUB_REF#refs/tags/}
-            BRANCH_NAME=$(git branch -r --contains tags/$TAG_NAME | grep -v 'HEAD' | head -n 1 | sed 's/origin\///' | xargs)
-            if [ -z "$BRANCH_NAME" ]; then
-              echo "Branch not found for tag $TAG_NAME"
-              exit 1
-            fi
-          fi
-          echo "::set-output name=branch::$BRANCH_NAME"
+      # - uses: actions/checkout@v4
+      # - name: Extract branch name from tag reference
+      #   id: extract_branch
+      #   run: |
+      #     if [[ $GITHUB_REF =~ refs/tags/release\.([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+      #       BRANCH_NAME="main"
+      #     elif [[ $GITHUB_REF =~ refs/tags/release\.([0-9]+)\.([0-9]+)\.([0-9]+)-rc\.([0-9]+)$ ]]; then
+      #       X=${BASH_REMATCH[1]}
+      #       Y=${BASH_REMATCH[2]}
+      #       Z=${BASH_REMATCH[3]}
+      #       BRANCH_NAME="release/$X.$Y.$Z"
+      #     else
+      #       TAG_NAME=${GITHUB_REF#refs/tags/}
+      #       BRANCH_NAME=$(git branch -r --contains tags/$TAG_NAME | grep -v 'HEAD' | head -n 1 | sed 's/origin\///' | xargs)
+      #       if [ -z "$BRANCH_NAME" ]; then
+      #         echo "Branch not found for tag $TAG_NAME"
+      #         exit 1
+      #       fi
+      #     fi
+      #     echo "::set-output name=branch::$BRANCH_NAME"
 
       - name: Set up Git identity
         run: |
@@ -38,8 +38,8 @@ jobs:
 
       - name: Checkout Repo
         uses: actions/checkout@v4
-        with:
-          ref: ${{ steps.extract_branch.outputs.branch }}
+        # with:
+        #   ref: ${{ steps.extract_branch.outputs.branch }}
 
       - name: Setup Node.js
         uses: actions/setup-node@v4
@@ -92,8 +92,8 @@ jobs:
       - name: Git status
         run: git status
 
-      # - name: Git Push
-      #   run: git push origin HEAD:${{ github.ref }}
+      - name: Git Push
+        run: git push origin release-candidate
 
       # This expects you to have a script called release which does a build for your packages and calls changeset publish
 
